### ISSUE TITLE
Imágenes de perfil

### ISSUE THREAD

**Issue by matiquec** [G8-Grupo-61/salud_a_la_mesa#11]
Requerimos imágenes adecuadas para mantener la estética del sitio en los perfiles de equipo

Validación
- 5 imágenes de cada uno en tamaño 200x200
- Entrega para viernes 17/09/21 antes de las 5 pm

**Comment by GabrielRinconv** [comment]
Gabriel Rincón
Estudiante de Ing. Topográfica, con interés de aprender sobre geomática y SIG. Me gustan los videojuegos, el futbol, salir de viaje, conocer nuevos lugares y disfrutar del tiempo con las personas que aprecio.
![Foto_perfil_SAM](https://user-images.githubusercontent.com/86615979/133837602-9e9f0baa-9eb8-4e28-9850-6d8e930f02df.png)
