### ISSUE TITLE
Asesoría nutricional

### ISSUE THREAD

**Issue by matiquec** [G8-Grupo-61/salud_a_la_mesa#6]
Yo como usuario del sitio de salud a la mesa deseo que al hacer clic en la tarjeta de servicios de "Asesoría Nutricional" el sistema me lleve a la sección dónde esté la información nutricional de los diferentes productos que se venden en la tienda y de los que aunque no están, sean relevantes para mi nutrición y con esto poder iniciar o continuar con una vida más saludable.

Validación
- Contar con una sección de asesoría
- Mostrar un calendario con disponibilidad horaria
- Mostrar el personal

**Comment by glgomezm** [comment]
Asesoría nutricional
 
![image](https://user-images.githubusercontent.com/83614495/134072412-47c8a535-1632-4ae0-9466-43f108970f28.png)

Mantener hábitos saludables a lo largo de los años es esencial para que eleves tu calidad de vida y cuides de tu salud. Por eso, cuando de bienestar se trata lo mejor es llevar una alimentación balanceada, realizar actividad física y evitar prácticas nocivas para la salud. 

¿Qué es la obesidad y cuáles son sus riesgos? 
De acuerdo con la Organización Mundial de la Salud (OMS) es una enfermedad que se caracteriza por una acumulación excesiva de grasa en el cuerpo. Aunque muchos suelen creer que es, exclusivamente, un problema estético lo cierto es que puede acarrear el desarrollo de patologías más graves como: 
•	Diabetes mellitus tipo 2 e hipertensión arterial. 
•	Dolor en las articulaciones y artrosis. 
•	Enfermedad cardíaca coronaria que puede desencadenar en infarto. 
•	Apnea del sueño, es decir, pausas en la respiración mientras duermes.   
•	Dolor de espalda  y dificultad para respirar. 
•	En las mujeres aumenta la probabilidad de complicaciones durante y después del embarazo.  
•	Problemas mentales como ansiedad y depresión.  

¡Tú puedes prevenirla! 
Porque todo comienza con el autocuidado, te traemos algunos ‘tips’ para que mantengas un peso saludable: 
•	Organiza tu alimentación y limita el consumo de productos ricos en azúcares y grasas. 
•	Incluye en tu dieta diaria frutas, verduras, proteínas magras, legumbres, cereales integrales y frutos secos. 
•	Mantente activo. Realiza actividad física frecuentemente. Lo recomendable son 60 minutos diarios para los jóvenes y 150 minutos semanales para los adultos.  
•	Dile no al tabaquismo que está asociado con múltiples enfermedades, pero también con el aumento de peso. 
•	Visita regularmente a tu médico de confianza y realízate los chequeos necesarios. 
Por último, controla el hambre emocional, si sientes ansiedad, es una pésima idea que comas por este impulso. Para esto, te recomendamos que tomes dos refrigerios saludables a lo largo del día entre comidas.
